### ISSUE TITLE
Why a copy is performed in move assignment implementation?

### ISSUE THREAD

**Issue by zerkms** [rmartinho/flamingdangerzone#2]
In the following article https://rmf.io/cxx11/rule-of-zero/ you implemented a move assignment in this way:

```c++
module& operator=(module&& that) {
    module copy { std::move(that) };
    std::swap(handle, copy.handle);
    return *this;
}
```

What purpose does the copying here serve? Could it not just be `std::swap(handle, that.handle);`?

Thanks

**Comment by developerbmw** [comment]
If it were just `std::swap(handle, that.handle);` then the original `this->handle` will only be freed when `that` is destroyed. Ideally it should be freed when the move is actually performed.

Is this correct?

**Comment by rmartinho** [comment]
Yes, exactly. When you use assignment you fully expect the left hand side to be lost, not given to the right hand side. Giving `op=` the same semantics as swap is confusing, and should not be done, IMO.

**Comment by zerkms** [comment]
Cool, thanks.

**Comment by gnzlbg** [comment]
I end up writing move assignment as just:

```c++
module& operator=(module that) {
    std::swap(handle, copy.handle);
    return *this;
}
```

**Comment by zerkms** [comment]
@gnzlbg would it work if the `module` is not copyable? Would it even be treated as a move assignment? (its signature does not look so)

**Comment by gnzlbg** [comment]
>@gnzlbg would it work if the module is not copyable? Would it even be treated as a move assignment? (its signature does not look so)

Sure. If the module is only movable then `module& operator=(module)` will only work on rvalues and they will be moved. `operator=` and the constructors are _just_ functions. They are called _special member functions_ because the compiler might generate them for you but that is as _special_ as they get. Overloading resolution works as usual.

**Comment by developerbmw** [comment]
@gnzlbg It's not clear to someone else looking at your code that it's a move assignment since it doesn't follow the usual signature.

**Comment by gnzlbg** [comment]
@developerbmw if you just need to make a type copy/move assignable fast, and the type already has copy/move constructors, this is a not-very-efficient but very simple solution that allows you to reuse all of the copy/move constructors code. 

Readers that just want to use the type are typically only interested if the type is `SemiRegular` (which requires `MoveAssignable`), and this is really easy to check (just `require`/`static_assert` on it).

If the reader is interested in knowing _exactly_ how the type works and doesn't know this idiom you make a very good point, but arguably arguably the same argument can be made about other idioms like copy-and-swap, and a similar argument can be made about any type that has user defined special member functions (one has to work through them anyways).
